export default [
    {
        id: 1,
        username: "john_doe",
        email: "john.doe@email.com",
        password: "hashed_password_1",
        dob: "1990-05-15",
        gender: "Male",
        height: 175,
        weight: 70,
        rating: 4.5,
        budget: 1000,
        bio: "I love fashion and exploring new styles!",
        profile_pic: "https://example.com/john_doe_profile.jpg",
        profile_visibility: true,
    },
    {
        id: 2,
        username: "jane_smith",
        email: "jane.smith@email.com",
        password: "hashed_password_2",
        dob: "1988-12-10",
        gender: "Female",
        height: 160,
        weight: 55,
        rating: 4.8,
        budget: 1200,
        bio: "Fashion enthusiast and fitness lover!",
        profile_pic: "https://example.com/jane_smith_profile.jpg",
        profile_visibility: true,
    },
    {
        id: 3,
        username: "sam_wilson",
        email: "sam.wilson@email.com",
        password: "hashed_password_3",
        dob: "1995-03-22",
        gender: "Male",
        height: 180,
        weight: 85,
        rating: 4.2,
        budget: 800,
        bio: "Explorer of trends and outdoor activities.",
        profile_pic: "https://example.com/sam_wilson_profile.jpg",
        profile_visibility: true,
    },
    {
        id: 4,
        username: "lisa_jones",
        email: "lisa.jones@email.com",
        password: "hashed_password_4",
        dob: "1987-07-05",
        gender: "Female",
        height: 165,
        weight: 60,
        rating: 4.6,
        budget: 1500,
        bio: "Passionate about style and creativity.",
        profile_pic: "https://example.com/lisa_jones_profile.jpg",
        profile_visibility: true,
    },
    {
        id: 5,
        username: "michael_smith",
        email: "michael.smith@email.com",
        password: "hashed_password_5",
        dob: "1992-09-18",
        gender: "Male",
        height: 175,
        weight: 78,
        rating: 4.4,
        budget: 1100,
        bio: "Fashion and tech enthusiast with a keen eye for trends.",
        profile_pic: "https://example.com/michael_smith_profile.jpg",
        profile_visibility: true,
    },
];
